In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
trainset=pd.read_csv('train.csv')
trainset.head()

,customer_id,Name,age,gender,security_no,region_category,membership_category,joining_date,joined_through_referral,referral_id,...,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score
0,fffe4300490044003600300030003800,Pattie Morrisey,18,F,XW0DQ7H,Village,Platinum Membership,2017-08-17,No,xxxxxxxx,...,300.63,53005.25,17.0,781.75,Yes,Yes,No,Not Applicable,Products always in Stock,2
1,fffe43004900440032003100300035003700,Traci Peery,32,F,5K0N3X1,City,Premium Membership,2017-08-28,?,CID21329,...,306.34,12838.38,10.0,NaN,Yes,No,Yes,Solved,Quality Customer Care,1
2,fffe4300490044003100390032003600,Merideth Mcmeen,44,F,1F2TCL3,Town,No Membership,2016-11-11,Yes,CID12313,...,516.16,21027.00,22.0,500.69,No,Yes,Yes,Solved in Follow-up,Poor Website,5
3,fffe43004900440036003000330031003600,Eufemia Cardwell,37,M,VJGJ33N,City,No Membership,2016-10-29,Yes,CID3793,...,53.27,25239.56,6.0,567.66,No,Yes,Yes,Unsolved,Poor Website,5
4,fffe43004900440031003900350030003600,Meghan Kosak,31,F,SVZXCWB,City,No Membership,2017-09-12,No,xxxxxxxx,...,113.13,24483.66,16.0,663.06,No,Yes,Yes,Solved,Poor Website,5

In [3]:
trainset.shape

(36992, 25)

In [4]:
trainset.isnull().any()

customer_id                     False
Name                            False
age                             False
gender                          False
security_no                     False
region_category                  True
membership_category             False
joining_date                    False
joined_through_referral         False
referral_id                     False
preferred_offer_types            True
medium_of_operation             False
internet_option                 False
last_visit_time                 False
days_since_last_login           False
avg_time_spent                  False
avg_transaction_value           False
avg_frequency_login_days        False
points_in_wallet                 True
used_special_discount           False
offer_application_preference    False
past_complaint                  False
complaint_status                False
feedback                        False
churn_risk_score                False
dtype: bool

In [5]:
trainset.drop('referral_id',axis=1,inplace=True)
trainset.drop('security_no',axis=1,inplace=True)
trainset.drop('joining_date',axis=1,inplace=True)
trainset.drop('customer_id',axis=1,inplace=True)
trainset.drop('Name',axis=1,inplace=True)

In [6]:
jf=np.array(trainset['joined_through_referral'])
jf[jf=="?"]=np.nan
trainset['joined_through_referral']=jf
trainset['joined_through_referral'].head()

0     No
1    NaN
2    Yes
3    Yes
4     No
Name: joined_through_referral, dtype: object

In [7]:
trainset['joined_through_referral']=trainset['joined_through_referral'].fillna(value=trainset['joined_through_referral'].mode().iloc[0])
trainset['joined_through_referral'].head()

0     No
1     No
2    Yes
3    Yes
4     No
Name: joined_through_referral, dtype: object

In [8]:
mo=np.array(trainset['medium_of_operation'])
mo[mo=="?"]=np.nan
trainset['medium_of_operation']=mo
trainset['medium_of_operation'].head()

0           NaN
1       Desktop
2       Desktop
3       Desktop
4    Smartphone
Name: medium_of_operation, dtype: object

In [9]:
trainset['medium_of_operation']=trainset['medium_of_operation'].fillna(value=trainset['medium_of_operation'].mode().iloc[0])
trainset['medium_of_operation'].head()

0       Desktop
1       Desktop
2       Desktop
3       Desktop
4    Smartphone
Name: medium_of_operation, dtype: object

In [10]:
g=np.array(trainset['gender'])
g[g=="Unknown"]=np.nan
trainset['gender']=g
trainset['gender'].head()

0    F
1    F
2    F
3    M
4    F
Name: gender, dtype: object

In [11]:
trainset['gender']=trainset['gender'].fillna(value=trainset['gender'].mode().iloc[0])
trainset['gender'].head()

0    F
1    F
2    F
3    M
4    F
Name: gender, dtype: object

In [12]:
trainset['region_category']=trainset['region_category'].fillna(value=trainset['region_category'].mode().iloc[0])
trainset['region_category'].head()

0    Village
1       City
2       Town
3       City
4       City
Name: region_category, dtype: object

In [13]:
trainset['membership_category'].unique()

array(['Platinum Membership', 'Premium Membership', 'No Membership',
       'Gold Membership', 'Silver Membership', 'Basic Membership'],
      dtype=object)

In [14]:
trainset['preferred_offer_types']=trainset['preferred_offer_types'].fillna(value=trainset['preferred_offer_types'].mode().iloc[0])

In [15]:
trainset.drop('last_visit_time',axis=1,inplace=True)

In [16]:
dl=np.array(trainset['days_since_last_login'])
dl[dl< 0] = 0
dl[dl==0]=dl.mean()
trainset['days_since_last_login']=dl
trainset['days_since_last_login'].head()

0    17
1    16
2    14
3    11
4    20
Name: days_since_last_login, dtype: int64

In [17]:
ats=np.array(trainset['avg_time_spent'])
ats[ats< 0] = 0
ats[ats==0]=ats.mean()
trainset['avg_time_spent']=ats
trainset['avg_time_spent'].head(5)

0    300.63
1    306.34
2    516.16
3     53.27
4    113.13
Name: avg_time_spent, dtype: float64

In [18]:
afl=np.array(trainset['avg_frequency_login_days'])
for i in range(len(afl)):
    if(afl[i]=="Error"):
        afl[i]="-1"

In [19]:
afl=afl.astype(float)
afl=afl.astype(int)
afl[afl<0]=afl.mean()
trainset['avg_frequency_login_days']=afl
trainset['avg_frequency_login_days'].head()

0    17
1    10
2    22
3     6
4    16
Name: avg_frequency_login_days, dtype: int32

In [20]:
pw=np.array(trainset['points_in_wallet'])
#pw[pw<1]=np.nan
for i in range(len(pw)):
    if(pw[i]<1):
        pw[i]=np.nan
trainset['points_in_wallet']=pw
trainset['points_in_wallet'].head()

0    781.75
1       NaN
2    500.69
3    567.66
4    663.06
Name: points_in_wallet, dtype: float64

In [21]:
trainset['points_in_wallet']=trainset['points_in_wallet'].fillna(value=trainset['points_in_wallet'].mean())
trainset['points_in_wallet'].head()

0    781.750000
1    690.354685
2    500.690000
3    567.660000
4    663.060000
Name: points_in_wallet, dtype: float64

In [22]:
fb=np.array(trainset['complaint_status'])
for i in range(len(fb)):
    if(fb[i]=="No Information Available"):
        fb[i]=np.nan
trainset['complaint_status']=fb
trainset['complaint_status'].head(10)

0         Not Applicable
1                 Solved
2    Solved in Follow-up
3               Unsolved
4                 Solved
5               Unsolved
6    Solved in Follow-up
7               Unsolved
8    Solved in Follow-up
9                    NaN
Name: complaint_status, dtype: object

In [23]:
trainset['complaint_status']=trainset['complaint_status'].fillna(value=trainset['complaint_status'].mode().iloc[0])
trainset['complaint_status'].head(10)

0         Not Applicable
1                 Solved
2    Solved in Follow-up
3               Unsolved
4                 Solved
5               Unsolved
6    Solved in Follow-up
7               Unsolved
8    Solved in Follow-up
9         Not Applicable
Name: complaint_status, dtype: object

In [24]:
trainset.isnull().any()

age                             False
gender                          False
region_category                 False
membership_category             False
joined_through_referral         False
preferred_offer_types           False
medium_of_operation             False
internet_option                 False
days_since_last_login           False
avg_time_spent                  False
avg_transaction_value           False
avg_frequency_login_days        False
points_in_wallet                False
used_special_discount           False
offer_application_preference    False
past_complaint                  False
complaint_status                False
feedback                        False
churn_risk_score                False
dtype: bool

In [25]:
trainset['gender'] = trainset['gender'].map({'M': 0, 'F': 1})
trainset.head()

,age,gender,region_category,membership_category,joined_through_referral,preferred_offer_types,medium_of_operation,internet_option,days_since_last_login,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score
0,18,1,Village,Platinum Membership,No,Gift Vouchers/Coupons,Desktop,Wi-Fi,17,300.63,53005.25,17,781.750000,Yes,Yes,No,Not Applicable,Products always in Stock,2
1,32,1,City,Premium Membership,No,Gift Vouchers/Coupons,Desktop,Mobile_Data,16,306.34,12838.38,10,690.354685,Yes,No,Yes,Solved,Quality Customer Care,1
2,44,1,Town,No Membership,Yes,Gift Vouchers/Coupons,Desktop,Wi-Fi,14,516.16,21027.00,22,500.690000,No,Yes,Yes,Solved in Follow-up,Poor Website,5
3,37,0,City,No Membership,Yes,Gift Vouchers/Coupons,Desktop,Mobile_Data,11,53.27,25239.56,6,567.660000,No,Yes,Yes,Unsolved,Poor Website,5
4,31,1,City,No Membership,No,Credit/Debit Card Offers,Smartphone,Mobile_Data,20,113.13,24483.66,16,663.060000,No,Yes,Yes,Solved,Poor Website,5

In [26]:
trainset['region_category'].unique()

array(['Village', 'City', 'Town'], dtype=object)

In [27]:
trainset['region_category'] = trainset['region_category'].map({'Village': 0, 'Town': 1,'City':2})
trainset.head()

,age,gender,region_category,membership_category,joined_through_referral,preferred_offer_types,medium_of_operation,internet_option,days_since_last_login,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score
0,18,1,0,Platinum Membership,No,Gift Vouchers/Coupons,Desktop,Wi-Fi,17,300.63,53005.25,17,781.750000,Yes,Yes,No,Not Applicable,Products always in Stock,2
1,32,1,2,Premium Membership,No,Gift Vouchers/Coupons,Desktop,Mobile_Data,16,306.34,12838.38,10,690.354685,Yes,No,Yes,Solved,Quality Customer Care,1
2,44,1,1,No Membership,Yes,Gift Vouchers/Coupons,Desktop,Wi-Fi,14,516.16,21027.00,22,500.690000,No,Yes,Yes,Solved in Follow-up,Poor Website,5
3,37,0,2,No Membership,Yes,Gift Vouchers/Coupons,Desktop,Mobile_Data,11,53.27,25239.56,6,567.660000,No,Yes,Yes,Unsolved,Poor Website,5
4,31,1,2,No Membership,No,Credit/Debit Card Offers,Smartphone,Mobile_Data,20,113.13,24483.66,16,663.060000,No,Yes,Yes,Solved,Poor Website,5

In [28]:
trainset.isnull().any()

age                             False
gender                          False
region_category                 False
membership_category             False
joined_through_referral         False
preferred_offer_types           False
medium_of_operation             False
internet_option                 False
days_since_last_login           False
avg_time_spent                  False
avg_transaction_value           False
avg_frequency_login_days        False
points_in_wallet                False
used_special_discount           False
offer_application_preference    False
past_complaint                  False
complaint_status                False
feedback                        False
churn_risk_score                False
dtype: bool

In [29]:
trainset['membership_category'].unique()

array(['Platinum Membership', 'Premium Membership', 'No Membership',
       'Gold Membership', 'Silver Membership', 'Basic Membership'],
      dtype=object)

In [30]:
trainset['membership_category'] = trainset['membership_category'].map({'Platinum Membership': 0, 'Premium Membership': 1,'No Membership':2,
                                                                      'Gold Membership':3,'Silver Membership':4,'Basic Membership':5})
trainset.head()

,age,gender,region_category,membership_category,joined_through_referral,preferred_offer_types,medium_of_operation,internet_option,days_since_last_login,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score
0,18,1,0,0,No,Gift Vouchers/Coupons,Desktop,Wi-Fi,17,300.63,53005.25,17,781.750000,Yes,Yes,No,Not Applicable,Products always in Stock,2
1,32,1,2,1,No,Gift Vouchers/Coupons,Desktop,Mobile_Data,16,306.34,12838.38,10,690.354685,Yes,No,Yes,Solved,Quality Customer Care,1
2,44,1,1,2,Yes,Gift Vouchers/Coupons,Desktop,Wi-Fi,14,516.16,21027.00,22,500.690000,No,Yes,Yes,Solved in Follow-up,Poor Website,5
3,37,0,2,2,Yes,Gift Vouchers/Coupons,Desktop,Mobile_Data,11,53.27,25239.56,6,567.660000,No,Yes,Yes,Unsolved,Poor Website,5
4,31,1,2,2,No,Credit/Debit Card Offers,Smartphone,Mobile_Data,20,113.13,24483.66,16,663.060000,No,Yes,Yes,Solved,Poor Website,5

In [31]:
trainset['joined_through_referral'] = trainset['joined_through_referral'].map({'Yes': 0, 'No': 1})
trainset.head()

,age,gender,region_category,membership_category,joined_through_referral,preferred_offer_types,medium_of_operation,internet_option,days_since_last_login,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score
0,18,1,0,0,1,Gift Vouchers/Coupons,Desktop,Wi-Fi,17,300.63,53005.25,17,781.750000,Yes,Yes,No,Not Applicable,Products always in Stock,2
1,32,1,2,1,1,Gift Vouchers/Coupons,Desktop,Mobile_Data,16,306.34,12838.38,10,690.354685,Yes,No,Yes,Solved,Quality Customer Care,1
2,44,1,1,2,0,Gift Vouchers/Coupons,Desktop,Wi-Fi,14,516.16,21027.00,22,500.690000,No,Yes,Yes,Solved in Follow-up,Poor Website,5
3,37,0,2,2,0,Gift Vouchers/Coupons,Desktop,Mobile_Data,11,53.27,25239.56,6,567.660000,No,Yes,Yes,Unsolved,Poor Website,5
4,31,1,2,2,1,Credit/Debit Card Offers,Smartphone,Mobile_Data,20,113.13,24483.66,16,663.060000,No,Yes,Yes,Solved,Poor Website,5

In [32]:
trainset['preferred_offer_types'].unique()

array(['Gift Vouchers/Coupons', 'Credit/Debit Card Offers',
       'Without Offers'], dtype=object)

In [33]:
trainset['preferred_offer_types'] = trainset['preferred_offer_types'].map({'Gift Vouchers/Coupons': 0, 'Credit/Debit Card Offers': 1,'Without Offers':2})
trainset.head()

,age,gender,region_category,membership_category,joined_through_referral,preferred_offer_types,medium_of_operation,internet_option,days_since_last_login,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score
0,18,1,0,0,1,0,Desktop,Wi-Fi,17,300.63,53005.25,17,781.750000,Yes,Yes,No,Not Applicable,Products always in Stock,2
1,32,1,2,1,1,0,Desktop,Mobile_Data,16,306.34,12838.38,10,690.354685,Yes,No,Yes,Solved,Quality Customer Care,1
2,44,1,1,2,0,0,Desktop,Wi-Fi,14,516.16,21027.00,22,500.690000,No,Yes,Yes,Solved in Follow-up,Poor Website,5
3,37,0,2,2,0,0,Desktop,Mobile_Data,11,53.27,25239.56,6,567.660000,No,Yes,Yes,Unsolved,Poor Website,5
4,31,1,2,2,1,1,Smartphone,Mobile_Data,20,113.13,24483.66,16,663.060000,No,Yes,Yes,Solved,Poor Website,5

In [34]:
trainset['medium_of_operation'].unique()

array(['Desktop', 'Smartphone', 'Both'], dtype=object)

In [35]:
trainset['medium_of_operation'] = trainset['medium_of_operation'].map({'Desktop': 0, 'Smartphone': 1,'Both':2})
trainset.head()

,age,gender,region_category,membership_category,joined_through_referral,preferred_offer_types,medium_of_operation,internet_option,days_since_last_login,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score
0,18,1,0,0,1,0,0,Wi-Fi,17,300.63,53005.25,17,781.750000,Yes,Yes,No,Not Applicable,Products always in Stock,2
1,32,1,2,1,1,0,0,Mobile_Data,16,306.34,12838.38,10,690.354685,Yes,No,Yes,Solved,Quality Customer Care,1
2,44,1,1,2,0,0,0,Wi-Fi,14,516.16,21027.00,22,500.690000,No,Yes,Yes,Solved in Follow-up,Poor Website,5
3,37,0,2,2,0,0,0,Mobile_Data,11,53.27,25239.56,6,567.660000,No,Yes,Yes,Unsolved,Poor Website,5
4,31,1,2,2,1,1,1,Mobile_Data,20,113.13,24483.66,16,663.060000,No,Yes,Yes,Solved,Poor Website,5

In [36]:
trainset['internet_option'].unique()

array(['Wi-Fi', 'Mobile_Data', 'Fiber_Optic'], dtype=object)

In [37]:
trainset['internet_option'] = trainset['internet_option'].map({'Wi-Fi': 0, 'Mobile_Data': 1,'Fiber_Optic':2})
trainset.head()

,age,gender,region_category,membership_category,joined_through_referral,preferred_offer_types,medium_of_operation,internet_option,days_since_last_login,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score
0,18,1,0,0,1,0,0,0,17,300.63,53005.25,17,781.750000,Yes,Yes,No,Not Applicable,Products always in Stock,2
1,32,1,2,1,1,0,0,1,16,306.34,12838.38,10,690.354685,Yes,No,Yes,Solved,Quality Customer Care,1
2,44,1,1,2,0,0,0,0,14,516.16,21027.00,22,500.690000,No,Yes,Yes,Solved in Follow-up,Poor Website,5
3,37,0,2,2,0,0,0,1,11,53.27,25239.56,6,567.660000,No,Yes,Yes,Unsolved,Poor Website,5
4,31,1,2,2,1,1,1,1,20,113.13,24483.66,16,663.060000,No,Yes,Yes,Solved,Poor Website,5

In [38]:
trainset['used_special_discount'] = trainset['used_special_discount'].map({'Yes': 0, 'No': 1})
trainset.head()

,age,gender,region_category,membership_category,joined_through_referral,preferred_offer_types,medium_of_operation,internet_option,days_since_last_login,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score
0,18,1,0,0,1,0,0,0,17,300.63,53005.25,17,781.750000,0,Yes,No,Not Applicable,Products always in Stock,2
1,32,1,2,1,1,0,0,1,16,306.34,12838.38,10,690.354685,0,No,Yes,Solved,Quality Customer Care,1
2,44,1,1,2,0,0,0,0,14,516.16,21027.00,22,500.690000,1,Yes,Yes,Solved in Follow-up,Poor Website,5
3,37,0,2,2,0,0,0,1,11,53.27,25239.56,6,567.660000,1,Yes,Yes,Unsolved,Poor Website,5
4,31,1,2,2,1,1,1,1,20,113.13,24483.66,16,663.060000,1,Yes,Yes,Solved,Poor Website,5

In [39]:
trainset['offer_application_preference'] = trainset['offer_application_preference'].map({'Yes': 0, 'No': 1})
trainset.head()

,age,gender,region_category,membership_category,joined_through_referral,preferred_offer_types,medium_of_operation,internet_option,days_since_last_login,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score
0,18,1,0,0,1,0,0,0,17,300.63,53005.25,17,781.750000,0,0,No,Not Applicable,Products always in Stock,2
1,32,1,2,1,1,0,0,1,16,306.34,12838.38,10,690.354685,0,1,Yes,Solved,Quality Customer Care,1
2,44,1,1,2,0,0,0,0,14,516.16,21027.00,22,500.690000,1,0,Yes,Solved in Follow-up,Poor Website,5
3,37,0,2,2,0,0,0,1,11,53.27,25239.56,6,567.660000,1,0,Yes,Unsolved,Poor Website,5
4,31,1,2,2,1,1,1,1,20,113.13,24483.66,16,663.060000,1,0,Yes,Solved,Poor Website,5

In [40]:
trainset['past_complaint'] = trainset['past_complaint'].map({'Yes': 0, 'No': 1})
trainset.head()

,age,gender,region_category,membership_category,joined_through_referral,preferred_offer_types,medium_of_operation,internet_option,days_since_last_login,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score
0,18,1,0,0,1,0,0,0,17,300.63,53005.25,17,781.750000,0,0,1,Not Applicable,Products always in Stock,2
1,32,1,2,1,1,0,0,1,16,306.34,12838.38,10,690.354685,0,1,0,Solved,Quality Customer Care,1
2,44,1,1,2,0,0,0,0,14,516.16,21027.00,22,500.690000,1,0,0,Solved in Follow-up,Poor Website,5
3,37,0,2,2,0,0,0,1,11,53.27,25239.56,6,567.660000,1,0,0,Unsolved,Poor Website,5
4,31,1,2,2,1,1,1,1,20,113.13,24483.66,16,663.060000,1,0,0,Solved,Poor Website,5

In [41]:
trainset['complaint_status'].unique()

array(['Not Applicable', 'Solved', 'Solved in Follow-up', 'Unsolved'],
      dtype=object)

In [42]:
trainset['complaint_status'] = trainset['complaint_status'].map({'Not Applicable': 0, 'Solved': 1,'Solved in Follow-up':2,'Unsolved':3})
trainset.head()

,age,gender,region_category,membership_category,joined_through_referral,preferred_offer_types,medium_of_operation,internet_option,days_since_last_login,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score
0,18,1,0,0,1,0,0,0,17,300.63,53005.25,17,781.750000,0,0,1,0,Products always in Stock,2
1,32,1,2,1,1,0,0,1,16,306.34,12838.38,10,690.354685,0,1,0,1,Quality Customer Care,1
2,44,1,1,2,0,0,0,0,14,516.16,21027.00,22,500.690000,1,0,0,2,Poor Website,5
3,37,0,2,2,0,0,0,1,11,53.27,25239.56,6,567.660000,1,0,0,3,Poor Website,5
4,31,1,2,2,1,1,1,1,20,113.13,24483.66,16,663.060000,1,0,0,1,Poor Website,5

In [43]:
trainset['feedback'].unique()

array(['Products always in Stock', 'Quality Customer Care',
       'Poor Website', 'No reason specified', 'Poor Product Quality',
       'Poor Customer Service', 'Too many ads', 'User Friendly Website',
       'Reasonable Price'], dtype=object)

In [44]:
trainset['feedback'] = trainset['feedback'].map({'Products always in Stock': 0, 'Quality Customer Care': 1,'Poor Website':2,'No reason specified':3,
                                                'Poor Product Quality':4,'Poor Customer Service':5,'Too many ads':6,'User Friendly Website':7,'Reasonable Price':8})
trainset.head()

,age,gender,region_category,membership_category,joined_through_referral,preferred_offer_types,medium_of_operation,internet_option,days_since_last_login,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score
0,18,1,0,0,1,0,0,0,17,300.63,53005.25,17,781.750000,0,0,1,0,0,2
1,32,1,2,1,1,0,0,1,16,306.34,12838.38,10,690.354685,0,1,0,1,1,1
2,44,1,1,2,0,0,0,0,14,516.16,21027.00,22,500.690000,1,0,0,2,2,5
3,37,0,2,2,0,0,0,1,11,53.27,25239.56,6,567.660000,1,0,0,3,2,5
4,31,1,2,2,1,1,1,1,20,113.13,24483.66,16,663.060000,1,0,0,1,2,5